### ISSUE TITLE
Typo in "podcasts" on the slide Actions

### ISSUE THREAD

**Issue by BOLT04** [eddiejaoude/devrel-presentation#7]
Hi @eddiejaoude 👋, 

I was checking out the slides and found a typo where it says "podtcasts":
![image](https://user-images.githubusercontent.com/18630253/82462887-0c566200-9ab4-11ea-8600-9df7dc470452.png)

Just creating an issue in case you didn't spot it 🙂.

**Comment by eddiejaoude** [comment]
Oh awesome! Thank you. I am presenting it later today, so perfect. Thank you 👍

**Comment by eddiejaoude** [comment]
Fixed, thanks again 🤓
